# Generated by Django 4.2.5 on 2023-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('name', models.TextField(max_length=255)),
                ('ph', models.IntegerField(max_length=10)),
            ],
        ),
    ]
