# Generated by Django 4.2.5 on 2023-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ph',
            field=models.IntegerField(),
        ),
    ]
