# Generated by Django 4.2.5 on 2023-10-18 08:26

from django.db import migrations, models
import watchapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0002_alter_student_ph'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=watchapp.models.getFileName)),
                ('description', models.TextField(max_length=600)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
